mbrainerd/tk-multi-publish2

python/tk_multi_publish2/__init__.py, python/tk_multi_publish2/dialog.py
Pre-populates the publisher if SGTK_PUBLISH_PRELOAD_PATH environ variable is found.
=> added a PRELOAD_SIGNALER to dialog which connects to on_drop

hooks/basic/create_version.py, python/tk_multi_publish2/processing/plugin.py
Needs changes from [tk-multi-reviewsubmission](https://github.com/mbrainerd/tk-multi-reviewsubmission/pull/2) for release. Please merge only after that pull request is done.
=> #556: call change_context of tk-multi-reviewsubmission per item

hooks/basic/create_version.py, hooks/path_info.py
updated tk-multi-publish2/hooks/path_info get_frame_number to return string, so as to preserve the frame padding
=> #bug-701: Preserve the frame padding in path_info get_frame_number

hooks/basic/create_version.py, hooks/basic/publish_files.py, hooks/basic/upload_version.py, hooks/maya/publish_files.py, python/tk_multi_publish2/base_hooks/publish_plugin.py
update create_version plugin to use updated review submission app, added undo method to create version.
Also, added input_path_override on item properties to change the input path of the version entity.
=> #766, #539: override sg_path_to_frames on the version entity, added undo to create_version hook

python/tk_multi_publish2/base_hooks/publish_plugin.py
Needs to be merged after [tk-core #21](https://github.com/mbrainerd/tk-core/pull/21)
=> #1114:; seal copied files on publish

hooks/path_info.py, hooks/publish.py, python/tk_multi_publish2/util.py
Can be enabled with 'seal_files' in show_preferences
=> #1249: disabling sealing of files by default. 

hooks/basic/collector.py
By validating raw value against all envs.
=> #1340: filtering items with similar extensions but different work_path_template

hooks/mari/collector.py
Also, swap channel, geo in item name.
=> #1372: mari collector - put layer under channel it belongs to

hooks/mari/collector.py
=> #1395: mari collector - add setting to check if layers should be collected

hooks/mari/collector.py, hooks/mari/publish_textures.py
Copy the rest from the immediate previous publish on disk. Warn that this is happening (using a pop-up for now)
If such a version does not exist, fail validation.
=> #1499: enable selected udim publish

hooks/publish.py
Merge https://github.com/mbrainerd/tk-core/pull/29 before this.
=> #1550: _get_publish_path() - for non-sequence items, set seq fields to None

hooks/basic/collector.py, hooks/nuke/collector.py
Needs https://github.com/mbrainerd/tk-config-default2/pull/137 to avoid validation errors.
=> #1786: add DeepWrite to nodes collected by nuke collector

hooks/basic/collector.py, hooks/basic/publish_files.py
made non-matching raw work_path_template as warning instead of error
=> #1818: added deep_render to default item types

hooks/mari/publish_textures.py
=> #2537: publish_textures - copy option was exporting as well

hooks/houdini/collector.py, hooks/mari/collector.py, hooks/maya/collector.py, hooks/nuke/collector.py
Since we are receiving plates with 07 padding,  defined a new key "ingestSEQ" for BNW show.
ingestSEQ:
type: sequence
format_spec: '07'
alias: SEQ
Added key existence check before removing it from fields.
=> #3141: modified code to check key existence

hooks/mari/collector.py, hooks/mari/publish_mipmaps.py, hooks/mari/publish_textures.py, hooks/path_info.py, python/tk_multi_publish2/util.py
Also, fix #3739: if no UDIMs are selected, create mipmaps for all
Needs https://github.com/mbrainerd/tk-core/pull/36
=> #3761:  hard link textures and mipmaps instead of symlink

hooks/basic/collector.py
if matched_work_path_template is none then UI pop-up with item_types.
User can choose required item type to be ingested.
=> #3188: added pop-up to choose the relevant item type

info.yml, python/tk_multi_publish2/__init__.py
To enable displaying the host name in the window title
=> added display_host_name setting

hooks/path_info.py, python/tk_multi_publish2/util.py
Added copy folder method in path info which allows us to copy folder during publish sessions.
=> #4696: Defined Copy_Folder method

hooks/path_info.py, python/tk_multi_publish2/util.py
Since we removed `code`, both version and extension got removed, and our publish names are not unique enough.
=> #5076: for higher version conflict, check possible publish path as well

hooks/basic/collector.py
Fixed tool to collect pre-defined extensions and mime-type extensions in upper_case also.
=> #4679: allow upper_case extensions for ingestion

hooks/mari/publish_textures.py
=> #5568: publish_textures - for single layer, handle by layer type
